New form
dellydel/Intro-to-HTML-and-JS pull request #19
Opened 2022-09-23 02:08 UTC by Puffin247

2022-09-23 21:20 UTC, dellydel requested changes
Looks good so far. For the gender radio button, make sure the labels are for "male" or "female". looks like all 3 just have the label of "gender". Make those updates and push again. Good work so far.

2022-09-26 21:26 UTC, dellydel requested changes

2022-09-26 21:26 UTC, dellydel commented on Sanya_form.HTML
> +      <b><label>Date_of_Birth:</label></b>
No need for the underscore in the label text. The user of your website will be able to see the label, so use plain text:  "Date of Birth"

2022-09-26 21:26 UTC, dellydel commented on Sanya_form.HTML
> +      <b><label>Gender:</label></b>
Looks like this gender label is out of place. It should be next to the radio buttons. If you view the page in a browser, you will see that it is not in the right place

2022-09-26 21:26 UTC, dellydel commented on Sanya_form.HTML
> +      <b><label>Other:</label></b>
This label seems to be out of place

2022-09-26 21:26 UTC, dellydel commented on Sanya_form.HTML
> +      <input type="submit" type="color-green">
You can only have one "type" attribute. I think you are looking for the "style" attribute

2022-09-27 17:08 UTC, dellydel requested changes

2022-09-27 17:08 UTC, dellydel commented on Sanya_form.HTML
>        <input type="mobile" />
"mobile" is not a type.  There is a type that you can use for telephone numbers though

2022-09-27 17:08 UTC, dellydel commented on Sanya_form.HTML
>        <input id="male" type="radio" />
This male radio button is not working properly

2022-09-27 17:08 UTC, dellydel commented on Sanya_form.HTML
>          <br/></b></b>
There are closing bold tags, but no opening tags. The bold tags can probably be removed

2022-09-28 15:42 UTC, dellydel requested changes

2022-09-28 15:42 UTC, dellydel commented on Sanya_form.HTML
>          <br/></b></b>
Excellent updates, there are just the two closing bold tags that can be removed here and then you are good to go!

2022-09-29 00:00 UTC, dellydel approved these changes
Excellent

2022-09-29 14:50 UTC, Puffin247 commented
Hi Del,

Why is my mering blocked?

2022-09-30 15:19 UTC, dellydel commented
> Hi Del,
> 
> Why is my mering blocked?

Your merge is blocked because you don't have the latest code from main. Remember you always need to have the latest code before you merge. This prevents merge conflicts. Pull from main, then merge those changes into your branch. or you can click on the update branch button on this page.

2022-10-01 15:42 UTC, merged