ADDED MY FORM
dellydel/Intro-to-HTML-and-JS pull request #32
Opened 2022-09-30 09:00 UTC by El-eric5

CREATED MY FORM

2022-09-30 15:04 UTC, dellydel requested changes

2022-09-30 15:04 UTC, dellydel commented on ERIC_FORM.html
> +  <input type="text" name="" id="Surname">
No need for the "name" attribute.  You can remove it, especially if it is empty.

2022-09-30 15:04 UTC, dellydel commented on ERIC_FORM.html
> +    <br>
Don't forget the slash here: < br />

2022-10-01 07:39 UTC, El-eric5 commented
eric math function

2022-10-01 16:01 UTC, El-eric5 commented
i just added math function to the form

2022-10-04 00:45 UTC, dellydel commented on ERIC_FORM.html
> +
Lots of extra space here, clean up the extra lines a bit here

2022-10-04 00:45 UTC, dellydel commented on Eric_maths.js
> +
Remove extra spaces here

2022-10-04 00:46 UTC, dellydel requested changes
Just some small changes and you are good to go... Don't forget to add the slash to your line break elements: <br / >

2022-10-06 00:55 UTC, dellydel approved these changes

2022-10-06 01:05 UTC, merged